%this script should help explain how to run the program on two surfaces; if
%you have a 64bit Windows machine then the programs are compiled and should run
%without any extra work; if you have a mac or a 32bit Windows machine you
%have to go through the entire compilation process, which is described in
%the Word file in the main folder;
clear
%----    Data Processing
% cd('C:/Users/student/Desktop/OneDrive - Florida State University/3DProteins/surface-sphericalmaps/probe-3.5')
% Proteins=[];
% load('1a49a-3.5.pm.mat')
% Proteins{1}=M;
% load('1amua-3.5.pm.mat')
% Proteins{2}=M;
% load('1ayla-3.5.pm.mat')
% Proteins{3}=M;
% load('1bdga-3.5.pm.mat')
% Proteins{4}=M;
% load('1cq1a-3.5.pm.mat')
% Proteins{5}=M;
% load('1cqxa-3.5.pm.mat')
% Proteins{6}=M;
% load('1ct9a-3.5.pm.mat')
% Proteins{7}=M;
% load('1d0ca-3.5.pm.mat')
% Proteins{8}=M;
% load('1d7ca-3.5.pm.mat')
% Proteins{9}=M;
% load('1dk0a-3.5.pm.mat')
% Proteins{10}=M;
% clear M;








%change this path to where this folder is stored on your computer; add Matlab path
%%addpath('C:/Users/student/Desktop/Xiaoming/ShapeAnalysis/Surface/Matlab/ClosedIan')
addpath('C:/Users/student/Desktop/OneDrive - Florida State University/Registration/Surface/Matlab/ClosedIan')
%addpath('C:/Users/student/Desktop/OneDrive - Florida State University/Registration/Surface/Matlab/Closed')

%change this path to where this folder is stored on your computer
%%cd('C:/Users/student/Desktop/Xiaoming/ShapeAnalysis/Surface/Matlab/ClosedIan')
cd('C:/Users/student/Desktop/OneDrive - Florida State University/Registration/Surface/Matlab/ClosedIan')


%load a few toy surfaces; Xdata is a cell where each entry is 50x50x3 closed
%surface
% load data.mat

%--------------------------------------

%generate the basis to search over the re-parameterization group; the
%inputs are the degree of spherical harmonics (5 is usually a good number)
%and the resolution of the surface grid; the outputs are the Theta x Phi
%grid, the spherical harmonics functions Psi and the basis b
[Theta,Phi,Psi,b]=spherharmbasis1(5,257);        %=spherharmbasis1(5,50);

%change this path to where this folder is stored on your computer
%cd('C:/Users/student/Desktop/Xiaoming/ShapeAnalysis/Surface/Mex/ClosedIan')
cd('C:/Users/student/Desktop/OneDrive - Florida State University/Registration/Surface/Mex/ClosedIan')


%this program optimally registers two surfaces and finds the distance
%between their shapes; the inputs are the two surfaces, the grid
%resolution, Theta, Phi, Psi, b generated by spherharmbasis1, a 0 or 1
%depending if you want to do initial dodecahedron grid rotation (for very
%similar surfaces like the medical ones we will study this can be set to 0
%to speed up the program) and the step size (.3 is usually a good value);
%the outputs are F2n the optimally registered second surface, F1 the first
%surface after translation and scaling, F2nb and F2nb1 the second surface
%before optimization over the re-parameterization group (F2nb1 is the same
%as F2nb if gridroteval is 0), H the final distance between the surfaces,
%Hstart the initial (before registration) distance between surfaces and
%gamcum the optimal re-parameterization grid; if you want to suppress
%figures change ShowFigures inside the program to 0 (there will still be 1
%figure that is displayed during each comparison that cannot be turned
%off); the output figures are 1: surface 1 with height function as colors,
%97: surface 2 prior to registration with height function from surface 1 mapped to corresponding
%points on surface 2, 98: same as 97, 100: this figure is the same as 97
%but changes during each iteration of the search over \Gamma, 99: same as
%97 but after optimal re-parameterization, 3: the optimal
%re-parameterization function, 5: evolution of the distance during search
%over rotation and re-parameterization group
% [F2n,F1,F2nb,F2nb1,H,Hstart,gamcum] = Compute_Elastic_Geod_Surf_Closednewq(Xdata{5},Xdata{1},50,Theta,Phi,Psi,b,0,.3);
%--F2n- 
%--F1
%--F2nb
%--F2nb1
%--H- final distance between surfaces
%--Hstart- initial distance between surfaces
%--gacum- optimal reparameterization grid
[F2n,F1,F2nb,F2nb1,H,Hstart,gamcum] = Compute_Elastic_Geod_Surf_Closednewq(pro1,pro2,257,Theta,Phi,Psi,b,0,.15);
H
% DisplaySurfaceClosed(pro2,0,124);
% 
% dispSurface222(F2n)

